services:
  phantombust.service:
    container_name: phantombust_service
    image: phantombust:1
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILE=${SPRING_PROFILE:-local}
      - JAVA_OPTS=${JAVA_OPTS}
    ports:
      - "8510:8510"
    networks:
      - phantombust_network
  phantombust.db:
    container_name: phantombust_db
    image: postgres:14-alpine
    restart: always
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - APP_DB_USER=phantombust
      - APP_DB_PASS=phantombust
      - APP_DB_NAME=phantombust
    ports:
      - '5430:5432'
    networks:
      - phantombust_network
    volumes:
      - pg_volume:/var/lib/postgresql/data
      - ./etc/postgres/pg_hba.conf:/etc/pg_hba.conf
      - ./db:/docker-entrypoint-initdb.d/
  phantombust.pgadmin:
    image: dpage/pgadmin4
    container_name: phantombust_pgadmin
    restart: always
    ports:
      - "6161:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: phantombust@treeshake.com.au
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - phantombust_network
    volumes:
      - pgadmin_volume:/var/data/pgadmin
networks:
  phantombust_network:
    name: phantombust_network
    driver: bridge
volumes:
  pg_volume:
    name: pg_volume
  pgadmin_volume:
    name: pgadmin_volume