spring:
  application:
    name: phantombust
  profiles:
    active: local
server:
  port: 1511
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://phantombust_db:5432/phantombust
    username: phantombust
    password: phantombust
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        jdbc:
          time_zone: UTC
  liquibase:
    enabled: true
    database-change-log-table: LIQUIBASE_DATABASE_CHANGE_LOG
    drop-first: false
    database-change-log-lock-table: LIQUIBASE_DATABASE_CHANGE_LOG_LOCK
    contexts: create
app:
  phantombuster:
    dataImport:
      followingCollectors:
        - https://cache1.phantombooster.com/1dpJXxCH7AU/Bgs6s6415dSUY8DY3ZSz5g/result.csv
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
    level:
      org.springframework.web: INFO
      guru.springframework.controllers: INFO
      org.hibernate: INFO
      liquibase: INFO